---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: Actualizar repositorios
      apt:
        update_cache: yes
      changed_when: false

  tasks:
    - name: Importar tareas de usuarios
      import_tasks: tareas/usuarios.yml

    - name: Importar tareas de cron
      import_tasks: tareas/cron.yml

    - name: Importar tareas de paquetes
      import_tasks: tareas/paquetes.yml
