---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: Actualizar caché de repositorios (Debian/Ubuntu)
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"
      changed_when: false

    - name: Actualizar caché de repositorios (Fedora/RedHat)
      dnf:
        update_cache: yes
      when: ansible_os_family == "RedHat"
      changed_when: false

    - name: Actualizar caché de repositorios (openSUSE)
      zypper:
        refresh: yes
      when: ansible_os_family == "Suse"
      changed_when: false

  tasks:
    - name: Importar tareas de usuarios
      import_tasks: tareas/usuarios.yml

    - name: Importar tareas de cron
      import_tasks: tareas/cron.yml

    - name: Importar tareas de paquetes
      import_tasks: tareas/paquetes.yml
